### ISSUE TITLE
Confusion about versioning scheme

### ISSUE THREAD

**Issue by oddlama** [Bastian/bStats-Metrics#100]
Hi there! I'm happily using bstats for my papermc plugin [vane](https://github.com/oddlama/vane), but I must admit that I am a little confused by the versioning at the moment and hope you can clear up the situation.

I'm currently using bstats 1.8, but I suppose 3.0.0 is the new version I should be using. Correct? I am confused because:
* `1.8` is the latest version available on [codemc](https://repo.codemc.io/service/rest/repository/browse/maven-public/org/bstats/bstats-bukkit/)
* `2.2.1` is written in the guide on your [own website](https://bstats.org/getting-started/include-metrics)
* while `3.0.0` is the latest release on github

Also when I try to use 3.0.0 from the maven repository, I seem to get a lite version where the custom chart classes like `SimplePie` are not included. So my question is, what is the actual recommended version and where can I acquire it including the chart classes?

**Comment by TheBusyBiscuit** [comment]
You will find bStats `1.8` on CodeMC because it used to be hosted there.
As of bStats `2.0.x` however, bStats is now hosted on maven-central. You can also browse the bStats artifacts here:
https://search.maven.org/search?q=g:org.bstats

Regarding the guide on the bStats website, it simply is out of date (version-wise, otherwise it is perfectly fine).
You could make a pull request to the [website repo](https://github.com/Bastian/bStats) and update that if you want. However keep in mind that Bastian was working on a new website for bStats anyway, so that repo may not get as much attention anymore.

Anyway, the most recent version of bStats is in fact `3.0.0` and I reckon it would be best to use that version and stay up to date with your dependencies. As to why your chart classes aree missing, I have no clue. If you provide a link here to the set up where you encountered this issue (perhaps a branch or commit), then someone might be able to help you out.

**Comment by oddlama** [comment]
Thanks for the swift response.

> Anyway, the most recent version of bStats is in fact 3.0.0 and I reckon it would be best to use that version and stay up to date with your dependencies. As to why your chart classes aree missing, I have no clue. If you provide a link here to the set up where you encountered this issue (perhaps a branch or commit), then someone might be able to help you out.

Alright, I also thought so and obviously would like to keep my deps updated. The only thing I changed was modifying the bstats version in my `build.gradle.kts` file to from `1.8` to `3.0.0`:

```diff
# vane-core/build.gradle.kts:
-    implementation(group = "org.bstats", name = "bstats-bukkit", version = "1.8")
+    implementation(group = "org.bstats", name = "bstats-bukkit", version = "3.0.0")
```

If you'd like to verify this in my repository, you can very easily do so:
```
https://github.com/oddlama/vane && cd vane
# replace bstats version in vane-core/build.gradle.kts
./gradlew build.
```

If you inspect the downloaded Metrics jar, you will see that only the Metrics class is included.

**Comment by TheBusyBiscuit** [comment]
Oh, you are upgrading from bStats 1.8.
In this case, you will need to make sure to include the bStats base module when shading/shadowing dependencies, e.g.

```gradle
shadowJar {
    dependencies {
        include (dependency('org.bstats:bstats-bukkit'))
        include (dependency('org.bstats:bstats-base'))
  }
  relocate 'org.bstats', 'YOUR_PATH.bstats'
}
```

As custom chart classes are shared across the different modules, they are located in the base module.
You don't need any other dependencies aside from `bstats-bukkit`, implemented as you posted:

```gradle
implementation(group = "org.bstats", name = "bstats-bukkit", version = "3.0.0")
```

But you will need to make sure that the bstats-base classes get shaded and relocated properly.

**Comment by oddlama** [comment]
Ah I see, thanks!

> But you will need to make sure that the bstats-base classes get shaded and relocated properly.

Yeah that's no problem, I was just missing the information that this is needed.
