### ISSUE TITLE
Server Version not counting

### ISSUE THREAD

**Issue by ShaneBeee** [Bastian/bStats-Metrics#45]
Am I crazy or is something wrong with the server version pie chart?

I use the default Spigot metrics class, with only one change (plugin name, added + "-ReRelease")
Everything else on there seems accurate, but for the server version pie it shows spigot and only 2 servers, where as (at the time of me posting this) there are 86 servers connected.
[GriefPreventionFlags-ReRelease](https://bstats.org/plugin/bukkit/GriefPreventionFlags-ReRelease)

Heres a link to my [REPO](https://github.com/ShaneBeee/GriefPreventionFlags) if anyone wants to see in the event something is wrong with my metrics class.

Thank you for reading!

**Comment by ShaneBeee** [comment]
I just checked it to be sure, and yes I am using the latest

**Comment by Bastian** [comment]
That's because of how bStats works. There's only one plugin on the server that submits the data for all the other plugins, so it can happen, that you are using the latest bStats version but the data is still sent by another plugin that's using an older version. I would recommend to just wait a few more weeks until more plugins updated their bStats class. 

2 out of 86 seems pretty low though, but your Metrics class in the repo looks fine.

**Comment by ShaneBeee** [comment]
> That's because of how bStats works. There's only one plugin on the server that submits the data for all the other plugins, so it can happen, that you are using the latest bStats version but the data is still sent by another plugin that's using an older version. I would recommend to just wait a few more weeks until more plugins updated their bStats class.
> 
> 2 out of 86 seems pretty low though, but your Metrics class in the repo looks fine.

OHHHHHHHH okay, this I did not know.
Thank you for clarifying that.
