### ISSUE TITLE
No option to opt out. 

### ISSUE THREAD

**Issue by New-Phoenix** [Bastian/bStats-Metrics#68]
There is literally no option to opt out. I would really appreciate one.
I really feel miserable and let down because of this :(
Now, I would be fine without doing so if it wouldn't collect information about my OS, architecture, etc,
and that bound with my real IP in case of a leak is serious info
![image](https://user-images.githubusercontent.com/62664720/83288929-3560ac00-a1b2-11ea-8a0f-e6b3cce211c0.png)
I changed the uuid so you wouldn't know who I am ;)
Please make one available
I have been messing with the config file adding things like enabled: false at places for a few days straight, no luck (I also tried messing with it trying to get getting the plugin to crash)
I don't know Java so please don't reply with a bunch of code that you're supposed to stick in who knows where
thanks

**Comment by Bastian** [comment]
Hey.
what server software are you using (Bukkit/Spigot, Bungeecord, Sponge, etc.)?

**Comment by New-Phoenix** [comment]
> Hey.
> what server software are you using (Bukkit/Spigot, Bungeecord, Sponge, etc.)?
Spigot (ChatControl plugin is the one adding bStats for me, I'm pretty sure)

**Comment by New-Phoenix** [comment]
> Hey.
> what server software are you using (Bukkit/Spigot, Bungeecord, Sponge, etc.)?

And also I hate the way blocking bStats in iptables stops the server from starting

**Comment by Bastian** [comment]
Thank you for reporting!

I took a look at the `ChatControl` plugin and noticed that it removed the option to disable bStats.
I will take immediate action and ban the author from bStats and delete the plugin.

However, this will not prevent the plugin from sending data. I recommend you to remove the plugin from your server until the plugin author has removed bStats.

**Comment by kangarko** [comment]
I'd like to personally apology for that we disabled the ability for the user to stop their data from being sent to bStats.

I understand that was not a fair move and was extremely disrespectful to the user's choice of privacy. I just wanted to follow up on this an apology to Bastian, but most importantly, I want to apology to everyone affected.

Last week, I changed our company's infrastructure and policies, and the developers maintaining ChatControl (among other plugins) are no longer associated with MineAcademy. I personally removed all traces of sending bStats from our software.

**Comment by Bastian** [comment]
Hi Matej,

thank you very much for your apology. I appreciate your response!

With that said, I have one small request remaining: Your [`Foundation`](https://github.com/kangarko/Foundation) library still has bStats' disable functionality removed. Besides this obvious "issue", I would like bStats to be removed from the `Foundation` library completely because modified versions of the Metrics class make it hard for me to ensure backward- and forward compatibility when releasing updates.

Additionally, modified Metrics classes often contain bugs because people don't fully understand how they work*. I've had some bad experiences with modified versions even from very popular projects with skilled developers (e.g., [Paper](https://github.com/PaperMC/Paper/issues/646)) and I don't have the time (or motivation) to review custom implementations. Adding bStats into a plugin with a proper build automation tool like Gradle or Maven is super easy, so the benefit of including it in your library is probably negligible.

Thanks!

_*The Metrics classes also communicate with each other and not just send data to the server. There's some magic with reflection and Bukkit's services manager happening. It's not super complicated but easy to break if you don't pay attention._ 

PS: If you want to, you can re-add ChatControl to bStats without any modifications to the Metrics class.

**Comment by kangarko** [comment]
Hi Bastian,

I reviewed the affected class and copy-pasted your latest version, you were right, the "enabled" field has been missing! Our plugins had the class disabled even before that, but now this change will apply for everyone using Foundation.

I totally understand how frustrating it is to debug and solve issues for modified versions of bStats classes, especially given these are out of your control and definitely out of your scope of responsibility/time frame. 

Temporarily, I placed a heavily visible non-modification as well as legal disclaimer to the class multiple places. Simply removing it would mean every student has to update their pom.xml as well as make the code edits which would lead to confusion and problems. However, I will be dropping the built-in class in my next course update and force users to use the official version from your Maven repository completely. Thank you for making bStats.

Thank you very much, yes readding ChatControl back would be awesome :)

Matej
