### ISSUE TITLE
New versions of my plugin don't seem to be recognized

### ISSUE THREAD

**Issue by Sataniel98** [Bastian/bStats-Metrics#75]
Hello there,

my plugin is https://bstats.org/plugin/bukkit/DungeonsXL/1039.

I'm a bit puzzled that my plugin has lost about 200 servers (nearly half of its users) since August. I suspected the end of some kind of bump caused by people staying at home during the Corona crisis, but the number kept on dwindling.

Now I noticed that none of the newest versions are included in the plugin version pie chart, so I believe something I did in the most recent builds made it stop working. Build 1003 was the last of the ones I uploaded to SpigotMC.org that is included and since then, 8 new builds published there don't appear.

I suspect that the issue has something to do with the way I shade my libraries. I handle bStats through my DRECommons library (https://github.com/DRE2N/DRECommons/blob/master/core/src/main/java/de/erethon/commons/javaplugin/DREPlugin.java#L70), which itself relocates Metrics to de.erethon.commons.bstats (https://github.com/DRE2N/DRECommons/blob/master/dist/pom.xml#L36).

DungeonsXL relocates the whole de.erethon.commons package to de.erethon.dungeonsxl.util.commons. As of some time ago, I stopped relocating de.erethon.commons because of some issues with my setup of the new API module of DungeonsXL. At the same time, I updated from bStats 1.5 to 1.7. As of the latest build (1059), it is relocated again because I suspected that caused the issues with bStats. However, despite being downloaded ~100 times, I still can't find build 1059 in my pie chart.

Debug shows that Metrics#getPluginData() returns data that makes sense and Metrics#isEnabled() is true after onEnable().

Could you please help me out by confirming if there's any data of builds as of 1026, or perhaps even give me a hint about what I'm doing wrong?

**Comment by TheBusyBiscuit** [comment]
I suppose the issue is actually much simpler than this.

You need to pass the **bStats project id** to the Metrics constructor.
In `DREPlugin.java` however you seem to pass a "spigot resource id" instead:
https://github.com/DRE2N/DRECommons/blob/master/core/src/main/java/de/erethon/commons/javaplugin/DREPlugin.java#L70

So I looked into your DungeonsXL repository and searched for this initialization and found this:
https://github.com/DRE2N/DungeonsXL/blob/ceb1df58b17115c4016096c6979ccaab7d23fe92/core/src/main/java/de/erethon/dungeonsxl/DungeonsXL.java#L197

You are setting the SpigotMC resource id to `9488`, which is in fact your resource id for SpigotMC, but sadly not your bStats project id.
So I reckon you may need to adjust your `DREPluginSettings` builder to include a bStats id too ;)

https://www.spigotmc.org/resources/dungeonsxl.9488/   (ID: 9488)
https://bstats.org/plugin/bukkit/DungeonsXL/1039 (ID: 1039)

**Comment by Sataniel98** [comment]
Ouch, I feel dumb now. Thank you very much :)
