### ISSUE TITLE
Exact info about what DrilldownPie does

### ISSUE THREAD

**Issue by Andre601** [Bastian/bStats-Metrics#77]
I was wondering, what a DrilldownPie chart actually does different compared to a simple or AdvancedPie chart.

Like what is the main "gimmic" of it?
And what I wonder even more is, what the different values in the `HashMap<String, HashMap<String, Integer>>` are actually used for.
Like which value is used for what in the chart?

What is even more frustrating is the fact, that the [Custom Charts section](https://bstats.org/help/custom-charts#os) talking about this Pie uses "Operating System" in the visual chart, but Java version within the code-snippet, which makes it harder to understand, which values are shown where in the pie chart.

**Comment by WalshyDev** [comment]
It's nice in order to generalise more specific information. For example, the Java version chart. It shows "Java 7", "Java 8", etc and when you click it (drill down) you can see the amount per specific version.

The first key is the more "general" term (So, like "Java 11") the second key is the more drilled down one so like "11_201" and then the value of course is just for the sum.

If you look at Slimefun we use it for different ticking rate:
Chart: https://bstats.org/plugin/bukkit/Slimefun/4574#tick_rate
Code: https://github.com/Slimefun/MetricsModule/blob/master/src/main/java/dev/walshy/sfmetrics/charts/TickRateChart.java

So we can see the general key like cargo, click it and see how common different tick rates are.

**Comment by Andre601** [comment]
So when I understand this right would this here create a chart, which on BStats has the title "Spigot" and depicts either "yes" or "no" depending on the isSpigot() boolean, and when clicking on the chart would it then depict the actual brand/Name?

```java
    metrics.addCustomChart(
        new Metrics.DrilldownPie("using_spigot", () -> {
          Map<String, Map<String, Integer>> map = new HashMap<>();
          Map<String, Integer> entry = new HashMap<>();
          entry.put(getServerVersion().getType().getName(), 1);
          
          if (getServerVersion().isSpigot()) {
            map.put("yes", entry);
          } else {
            map.put("no", entry);
          }
          
          return map;
        }));
```

**Comment by Andre601** [comment]
Also, does BStats allow to change the Chart-type through the plugin? E.g. I use SimplePie and now want to switch to the DrilldownPie, would BStats allow this by simply changing the type in the plugin, or would I need to alter this on BStats itself?

**Comment by Bastian** [comment]
I'm sorry for not answering this issue. :/

The whole frontend is currently get a redesign + rewrite and I will take care to write a better explanation about drilldown charts with a correct example. :)
